-- 매출액: 판매가PRODUCT.PRICE * 판매량 OFFLINE_SALE.SALES_AMOUNT
SELECT P.PRODUCT_CODE, (P.PRICE * OS.SALES_AMOUNT) AS SALES
FROM (SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS SALES_AMOUNT
      FROM OFFLINE_SALE
      GROUP BY PRODUCT_ID
) OS
LEFT JOIN PRODUCT P
ON OS.PRODUCT_ID = P.PRODUCT_ID
ORDER BY SALES DESC, P.PRODUCT_CODE