SELECT ID, FISH_NAME, LENGTH
FROM FISH_NAME_INFO A
JOIN FISH_INFO B
ON A.FISH_TYPE = B.FISH_TYPE
WHERE (B.LENGTH, B.FISH_TYPE) IN (SELECT MAX(LENGTH) AS LENGTH, FISH_TYPE
FROM FISH_INFO
GROUP BY FISH_TYPE)